num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))
menor = min(num1, num2, num3)
maior = max(num1, num2, num3)
print("O menor número é:", menor)
print("O maior número é:", maior)
